openapi: 3.0.2
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /test:
    post:
      tags:
        - test-controller
      summary: TEST ENDPOINT
      description: Defines a simple get operation with no inputs and a complex
      operationId: allOf
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Cat"
                - properties:
                    name:
                      type: string

      responses:
        "200":
          description: Base 200 response
          content:
            application/json:
              schema:
                properties:
                  name:
                    type: string
                    default: "a"
                allOf:
                  - $ref: "#/components/schemas/Dog"
  /single:
    post:
      tags:
        - test-controller
      summary: TEST ENDPOINT
      description: Defines a simple get operation with no inputs and a complex
      operationId: allOfSingle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                pet:
                  allOf:
                    - $ref: '#/components/schemas/Mice'

      responses:
        "200":
          description: Base 200 response
          content:
            application/json:
              schema:
                properties:
                  pet:
                    allOf:
                      - $ref: '#/components/schemas/Mice'

components:
  schemas:
    Cat:
      type: object
      properties:
        type:
          type: string
        foo:
          type: string
      description: Cat class
    Dog:
      type: object
      properties:
        type:
          type: string
        baz:
          type: string
      description: Dog class
    Mice:
      allOf:
        - $ref: "#/components/schemas/Cat"